apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "10.105.142.203"
    hostnames:
    - "lab-dev.oneconnectft.com.sg"
  containers:
  - name: proxy
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"
