kind: PersistentVolume
apiVersion: v1
metadata:
  name: esdata02-volume
  labels:
    type: local
spec:
  storageClassName: es-storage
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/elasticsearch/data/data02
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker02
