kind: PersistentVolume
apiVersion: v1
metadata:
  name: esmaster02-volume
  labels:
    type: local
spec:
  storageClassName: es-ms-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/elasticsearch/data/master02
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker02
