kind: PersistentVolume
apiVersion: v1
metadata:
  name: kbdata01-volume
  labels:
    type: local
spec:
  storageClassName: kb-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kibana/data/01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker03

